# this will be converted into a .csv file at some point

connected = "The bot has connected to the voice channel successfully."
errors = "There's been an error."
already_connected = "The bot has already connected to the voice channel."
need_connect = "The user must be connected to a voice channel to use this command."
bot_not_in_vc = "The bot must be connected to a voice channel to use this command."
disconnected = "The bot has disconnected from the voice channel successfully."
queue_empty = "The queue is currently empty."
skipping = "Skipping..."
pausing = "Pausing..."
resuming = "Resuming..."
queued = "Successfully queued!"
no_play = "The bot is not playing anything at this time."
value_must_be_larger = "The input value must be larger."
